### ISSUE TITLE
Panic with a certain gcg through scrabblecam (awaiting details)

### ISSUE THREAD

**Issue by domino14** [woogles-io/liwords#1364]
`2024/09/08 16:51:01 http: panic serving 10.0.1.195:12278: runtime error: slice bounds out of range [:8] with capacity 7 |  
-- | --`

```

goroutine 160384033 [running]:
--
  | 2024-09-08T12:51:01.009-04:00 | net/http.(*conn).serve.func1()
  | 2024-09-08T12:51:01.009-04:00 | /usr/local/go/src/net/http/server.go:1947 +0xbe
  | 2024-09-08T12:51:01.009-04:00 | panic({0x19684c0?, 0xc00f394048?})
  | 2024-09-08T12:51:01.009-04:00 | /usr/local/go/src/runtime/panic.go:785 +0x132
  | 2024-09-08T12:51:01.009-04:00 | go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.deferwrap1()
  | 2024-09-08T12:51:01.009-04:00 | /go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.29.0/trace/span.go:398 +0x25
  | 2024-09-08T12:51:01.009-04:00 | go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc00918ba00, {0x0, 0x0, 0x29de7c0?})
  | 2024-09-08T12:51:01.009-04:00 | /go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.29.0/trace/span.go:436 +0xa62
  | 2024-09-08T12:51:01.009-04:00 | panic({0x19684c0?, 0xc00f394048?})
  | 2024-09-08T12:51:01.009-04:00 | /usr/local/go/src/runtime/panic.go:785 +0x132
  | 2024-09-08T12:51:01.009-04:00 | go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.deferwrap1()
  | 2024-09-08T12:51:01.009-04:00 | /go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.29.0/trace/span.go:398 +0x25
  | 2024-09-08T12:51:01.009-04:00 | go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0091c21a0, {0x0, 0x0, 0xc00709e000?})
  | 2024-09-08T12:51:01.009-04:00 | /go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.29.0/trace/span.go:436 +0xa62
  | 2024-09-08T12:51:01.009-04:00 | panic({0x19684c0?, 0xc00f394048?})
  | 2024-09-08T12:51:01.009-04:00 | /usr/local/go/src/runtime/panic.go:785 +0x132
  | 2024-09-08T12:51:01.011-04:00 | github.com/domino14/macondo/game.(*Game).PlayTurn(0xc00912f400, 0x10)
  | 2024-09-08T12:51:01.011-04:00 | /go/pkg/mod/github.com/domino14/macondo@v0.9.8/game/game.go:969 +0x7e9
  | 2024-09-08T12:51:01.011-04:00 | github.com/domino14/macondo/game.(*Game).PlayLatestEvent(...)
  | 2024-09-08T12:51:01.011-04:00 | /go/pkg/mod/github.com/domino14/macondo@v0.9.8/game/game.go:921
  | 2024-09-08T12:51:01.011-04:00 | github.com/domino14/macondo/gcgio.(*parser).addEventOrPragma(0xc00052c5e8, 0xc013129110?, 0x8, {0xc00f9d4a10, 0x7, 0x7})
  | 2024-09-08T12:51:01.011-04:00 | /go/pkg/mod/github.com/domino14/macondo@v0.9.8/gcgio/gcg.go:300 +0x264c
  | 2024-09-08T12:51:01.011-04:00 | github.com/domino14/macondo/gcgio.(*parser).parseLine(0xc00052c5e8, 0xc009eab0e0, {0xc013129110?, 0xc002f5fd20?})
  | 2024-09-08T12:51:01.011-04:00 | /go/pkg/mod/github.com/domino14/macondo@v0.9.8/gcgio/gcg.go:508 +0xc5
  | 2024-09-08T12:51:01.011-04:00 | github.com/domino14/macondo/gcgio.ParseGCGFromReader(0xc009eab0e0, {0x1cbebe0, 0xc009d79500})
  | 2024-09-08T12:51:01.011-04:00 | /go/pkg/mod/github.com/domino14/macondo@v0.9.8/gcgio/gcg.go:609 +0x3f3
  | 2024-09-08T12:51:01.011-04:00 | github.com/woogles-io/liwords/pkg/omgwords.(*OMGWordsService).ImportGCG(0xc0003e1860, {0x1cdca58, 0xc00efb94d0}, 0xc009a6f680)
  | 2024-09-08T12:51:01.011-04:00 | /opt/program/pkg/omgwords/service.go:537 +0x237


```

**Comment by domino14** [comment]
fixed but we should just not allow longer racks, i think.
